# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KnNhuM4Tm4POARJ-o8sH3Bl47VX3ihPt
"""

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BIKERS CLUB CALIFORNIA</title>
</head>
<STYle>html{
    background-color: aqua;
}
h1{
    background-color: rgb(27, 26, 26);
    color: rgb(231, 234, 236);
    font-family: Georgia, 'Times New Roman', Times, serif;
    text-align: center;
}
  
    text align <center></center>
</style> 


<body>
    <h1>BIKER CLUB CALIFORNIA</h1
        <h1>CLUB DE MOTOCICLISTAS O CLUB DE MOTEROS ES UN GRUPO DE INDIVIDUOS ASOCIADOS POR COMPARTIR PRINCIPAL Y MUTUO INTERES POR LAS MOTOCILETAS Y LAS ACTIVIDADES RELACIOANDAS :</h1>
        <p>"BIENVENIDOS"</p>

    div style="text-align: center++;"
           <img src="imagenes/1612.S.03.V01.moto3.jpg" alt="" width="600" height="700">
           
           
           
           
           
        
        
        
</body>
</html>